---
- hosts: vm
  name: Playbook that installs packages and runs a shell script
  become: yes
  
  tasks:
          - name: Installing vim
            yum:
                    name: vim
                    state: present
          - name: Running the shell script
            shell: /script.sh
            register: result
  
          - debug:
                var: result
