# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "generic/fedora28"
  config.vm.box_version = "1.8.40
  config.vm.box_url = "https://vagrantcloud.com/generic/fedora28"
end
